$(caterwaul.js_ui(caterwaul.js_all())(function () {
  $('body').append(jquery in div(h1('Rather insane serialization test'),
                                 textarea.code *cols(90) *rows(20) *value('var a = [];\na.push(a);\nreturn a;'),
                                 button.serialize('Serialize'),
                                 textarea.serialized *cols(90) *rows(5)));

  $('button.serialize').click(delay in $('.serialized').val(rather_insane_serialization.serialize(new Function($('.code').val())())));
}));

// Generated by SDoc 
